### ISSUE TITLE
s3EnforceUserACL - False Positive

### ISSUE THREAD

**Issue by jamesfernando94** [accurics/terrascan#359]
* terrascan version: v1.1.0
* Operating System: Mac OS and on Github Actions Ubuntu

### Description
When running superlinter I believe this has flagged a false positive on the s3 bucket being able to be accessed by all AWS accounts

### What I Did
I ran `terrascan scan -t aws` on a main.tf file containing this:
```hcl
resource "aws_s3_bucket" "example" {
  bucket = "example_bucket"
  acl    = "private"
  versioning {enabled = true}
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
  policy = <<EOF
  {
    "Version":"2012-10-17",
    "Statement":[
      {
        "Sid":"DenyAllAccountAccess",
        "Effect":"Deny",
        "Action":["*"],
        "Resource":["*"]
      }
    ]
  }
EOF
}
```

then received the following error:
```
results:
  violations:
  - rule_name: s3EnforceUserACL
    description: S3 bucket Access is allowed to all AWS Account Users.
    rule_id: AWS.S3Bucket.DS.High.1043
    severity: HIGH
    category: S3
    resource_name: example
    resource_type: aws_s3_bucket
    file: main.tf
    line: 1
  count:
    low: 0
    medium: 0
    high: 1
    total: 1
```

When searching online I was unable to find instructions on how to fix or anymore details on the error message, 
Thanks in advance for any help
James
