### ISSUE TITLE
How to get rid of "Anonymous, public read access to a container and its blobs can be enabled in Azure Blob storage. This is only recommended if absolutely necessary."

### ISSUE THREAD

**Issue by judaondo** [accurics/terrascan#405]
* terrascan version: v1.1.0
* Operating System: ubuntu 18.04

### Description

I have this code inside an storageAccount module 

```
# Create an storage account
resource "azurerm_storage_account" "storage_account" {
  name                     = "${local.environment}${local.name}sa"
  resource_group_name      = local.resource_group_name
  location                 = local.location
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "RAGRS"
  min_tls_version          = "TLS1_2"
  allow_blob_public_access = false
  is_hns_enabled           = true
  tags                     = local.tags
}

resource "azurerm_storage_container" "container" {
  count                 = local.container_name != "" ? 1 : 0
  name                  = "${local.container_name}-cont"
  storage_account_name  = azurerm_storage_account.storage_account.name
  container_access_type = private
}
```

### What I Did

I run: 
```
terrascan scan -t azure
```

### What I get:

```
results:
  violations:
  - rule_name: reme_checkStorageContainerAccess
    description: Anonymous, public read access to a container and its blobs can be enabled in Azure Blob storage. This is only recommended if absolutely necessary.
    rule_id: accurics.azure.IAM.368
    severity: HIGH    category: Identity and Access Management
    resource_name: container
    resource_type: azurerm_storage_container
    file: modules/07_storageAccount/main.tf
    line: 31
  count:
    low: 0
    medium: 0
    high: 1
    total: 1
```

How do I remove this error? 

Thank you.
