### ISSUE TITLE
Feature request: scan sub-folders too

### ISSUE THREAD

**Issue by ismailyenigul** [accurics/terrascan#411]
* terrascan version: v1.2.0
* Operating System: Linux

### Description

terrascan scans only the base directory.  it does not check sub folders.

### What I Did

```
bash-5.0# ls -lR
.:
total 4
drwxr-xr-x    3 root     root            96 Nov 30 15:00 iam-pass-policy
-rw-r--r--    1 root     root          1664 Nov 30 13:02 security_group_ingress_anywhere_infra.tf

./iam-pass-policy:
total 4
-rw-r--r--    1 root     root           740 Nov 30 09:12 iam-password-policy.tf
bash-5.0# 

# terrascan scan .
results:
    violations:
        - rule_name: port80OpenToInternet
          description: http port open to internet
          rule_id: AWS.SecurityGroup.NetworkPortsSecurity.Low.0561
          severity: HIGH
          category: Network Ports Security
          resource_name: valid_exact_80
          resource_type: aws_security_group
          file: security_group_ingress_anywhere_infra.tf
          line: 18
        - rule_name: unknownPortOpenToInternet
          description: Unknown Port is exposed to the entire internet
          rule_id: AWS.SecurityGroup.NPS.High.1046
          severity: HIGH
          category: Network Ports Security
          resource_name: invalid_include_80
          resource_type: aws_security_group
          file: security_group_ingress_anywhere_infra.tf
          line: 29
        - rule_name: unknownPortOpenToInternet
          description: Unknown Port is exposed to the entire internet
          rule_id: AWS.SecurityGroup.NPS.High.1046
          severity: HIGH
          category: Network Ports Security
          resource_name: invalid_include_443
          resource_type: aws_security_group
          file: security_group_ingress_anywhere_infra.tf
          line: 51
        - rule_name: portWideOpenToPublic
          description: It is recommended that no security group allows unrestricted ingress access
          rule_id: AWS.SecurityGroup.NPS.High.1045
          severity: HIGH
          category: Network Ports Security
          resource_name: invalid_allow_all
          resource_type: aws_security_group
          file: security_group_ingress_anywhere_infra.tf
          line: 62
        - rule_name: portWideOpenToPublic
          description: It is recommended that no security group allows unrestricted ingress access
          rule_id: AWS.SecurityGroup.NPS.High.1045
          severity: HIGH
          category: Network Ports Security
          resource_name: invalid_include_80
          resource_type: aws_security_group
          file: security_group_ingress_anywhere_infra.tf
          line: 29
        - rule_name: portWideOpenToPublic
          description: It is recommended that no security group allows unrestricted ingress access
          rule_id: AWS.SecurityGroup.NPS.High.1045
          severity: HIGH
          category: Network Ports Security
          resource_name: invalid_include_443
          resource_type: aws_security_group
          file: security_group_ingress_anywhere_infra.tf
          line: 51
    count:
        low: 0
        medium: 0
        high: 6
        total: 6

```

terrascan only scans security_group_ingress_anywhere_infra.tf in the current path. never scan 
iam-pass-policy sub folder. I have to specify sub-folder.  Specifying multiple path with multiple `-d` parameters does not help.

```
# terrascan scan -d iam-pass-policy
results:
    violations:
        - rule_name: passwordReuseNotAllowed
          description: It is recommended that the password policy prevent the reuse of passwords.Preventing password reuse increases account resiliency against brute force login attempts
          rule_id: AWS.Iam.IAM.Low.0539
          severity: LOW
          category: IAM
          resource_name: good
          resource_type: aws_iam_account_password_policy
          file: iam-password-policy.tf
          line: 4
....
```
