### ISSUE TITLE
Admission Controller Doesn't display feedback for kubectl "create" and "apply"

### ISSUE THREAD

**Issue by amirbenv** [accurics/terrascan#731]
* terrascan version: 1.5.1
* Operating System: MacOS 11

### Description

When using kubectl to `create` or `apply`, admission controller responses are not being displayed to the user. 
If applicable, the `logs` endpoint shows the results. Enforcement also works.  

### What I Did

```
kubectl create -f vulnerable_pod.yaml
```

**Comment by amirbenv** [comment]
@alexfeig

**Comment by alexfeig** [comment]
Thanks @amirbenv - if you need a sample, here you go:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  namespace: default
spec:
  selector:
    matchLabels:
      app: green
  replicas: 2
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: alexfeig/bluegreen:latest
        ports:
        - containerPort: 5000
        env:
        - name: app_color
          value: "green"
```

**Comment by dev-gaur** [comment]
@alexfeig can you share the webhook yaml file ?

**Comment by dev-gaur** [comment]
webhooks:
  - name: terrascan-validating-hook.terrascan.svc
    rules:
    - apiGroups:
      - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
        - services

Did you try tinkering with these rule properties? maybe add deployment, secret, configmap, replicaset, replicacontroller in `webhooks.rules[0].resources` list ?

**Comment by alexfeig** [comment]
Sure, here you go. One thing is that using `kubectl run` works just fine, so I don't think it's the `ValidatingWebhookConfiguration`

```
  apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: terrascan.hook.all
  webhooks:
    - name: terrascan.hook.all
      rules:
        - apiGroups:
            - ""
          apiVersions:
            - v1
          operations:
            - CREATE
            - UPDATE
          resources:
            - "*"
      failurePolicy: Fail
      clientConfig:
        url: https://192.168.49.1:9443/v1/k8s/webhooks/12345/scan/validate
        caBundle: xxxx
      sideEffects: None
      admissionReviewVersions: ["v1"]
```
