### ISSUE TITLE
Terrascan requires key when setting encryption to true (ignoring AWS default key)

### ISSUE THREAD

**Issue by possani** [accurics/terrascan#801]
Terrascan running in ghcr.io/github/super-linter:v3.15.5

### Description

Terrascan requires a _kms_key_id_ when setting encryption to true.
According to the [resource description](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system#kms_key_id) both attributes are optional, but encryption has to be set to true when specifying a key. However, the other way around is not required since AWS will use the default key for encryption (i.e. AWS managed keys - aws/elasticfilesystem)

### What I Did

```
resource "aws_efs_file_system" "snap_maxio" {
  creation_token                  = var.some_token
  encrypted                       = true
  ...
}
```
Error:
```
results:
    violations:
        - rule_name: efsEncryptedWithNoKms
          description: Enable encryption of your EFS file systems in order to protect your data and metadata from breaches or unauthorized access and fulfill compliance requirements for data-at-rest encryption within your organization.
          rule_id: AWS.EFS.EncryptionandKeyManagement.High.0410
          severity: HIGH
          category: Data Protection
          resource_name: ...
          resource_type: aws_efs_file_system
          file: ...
          line: ...
```

**Comment by possani** [comment]
This also applies to _aws_secretsmanager_secret_:
```
results:
    violations:
        - rule_name: notEncryptedSecrets
          description: Ensure SecretsManager Secrets are Encrypted using KMS key
          rule_id: AWS.SecretsManagerSecret.DP.MEDIUM.0036
          severity: MEDIUM
          category: Data Protection
```
